export const LANGUAGES = [
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "cpp", label: "C++" },
  { value: "c", label: "C" },
  { value: "csharp", label: "C#" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "ruby", label: "Ruby" },
  { value: "php", label: "PHP" },
  { value: "swift", label: "Swift" },
  { value: "kotlin", label: "Kotlin" },
  { value: "dart", label: "Dart" },
  { value: "scala", label: "Scala" },
  { value: "r", label: "R" },
  { value: "lua", label: "Lua" },
  { value: "perl", label: "Perl" },
  { value: "haskell", label: "Haskell" },
  { value: "elixir", label: "Elixir" },
  { value: "clojure", label: "Clojure" },
  { value: "objective-c", label: "Objective-C" },
  { value: "bash", label: "Bash / Shell" },
  { value: "powershell", label: "PowerShell" },
  { value: "sql", label: "SQL" },
  { value: "graphql", label: "GraphQL" },
  { value: "html", label: "HTML" },
  { value: "css", label: "CSS" },
  { value: "scss", label: "SCSS / Sass" },
  { value: "json", label: "JSON" },
  { value: "xml", label: "XML" },
  { value: "yaml", label: "YAML" },
  { value: "toml", label: "TOML" },
  { value: "markdown", label: "Markdown" },
  { value: "dockerfile", label: "Dockerfile" },
  { value: "nginx", label: "Nginx Config" },
  { value: "terraform", label: "Terraform (HCL)" },
  { value: "protobuf", label: "Protocol Buffers" },
  { value: "solidity", label: "Solidity" },
  { value: "plaintext", label: "Plain Text" },
];

export const CATEGORIES = [
  { value: "bug-fix", label: "Bug Fix", icon: "🐛", color: "#ff4757" },
  { value: "snippet", label: "Snippet", icon: "✂️", color: "#7c5cfc" },
  {
    value: "architecture",
    label: "Architecture",
    icon: "🏗️",
    color: "#3b82f6",
  },
  { value: "command", label: "Command", icon: "💻", color: "#00d4aa" },
  { value: "config", label: "Config", icon: "⚙️", color: "#ffa502" },
  { value: "learning", label: "Learning", icon: "📚", color: "#2ed573" },
  { value: "other", label: "Other", icon: "📝", color: "#a0a0b8" },
];

export const CATEGORY_MAP = CATEGORIES.reduce((acc, c) => {
  acc[c.value] = c;
  return acc;
}, {});

// Predefined important developer tags for quick selection
export const PRESET_TAGS = [
  "javascript",
  "typescript",
  "python",
  "react",
  "nextjs",
  "nodejs",
  "express",
  "mongodb",
  "postgresql",
  "docker",
  "kubernetes",
  "git",
  "linux",
  "aws",
  "api",
  "graphql",
  "redis",
  "authentication",
  "performance",
  "security",
  "testing",
  "css",
  "tailwind",
  "devops",
  "database",
  "frontend",
  "backend",
  "algorithm",
  "debugging",
  "deployment",
];
