const keyword = require("keyword-extractor");

// Developer-specific dictionary for tag matching
const DEV_DICTIONARY = new Set([
  "react",
  "nextjs",
  "node",
  "express",
  "mongodb",
  "mongoose",
  "docker",
  "kubernetes",
  "redis",
  "jwt",
  "auth",
  "api",
  "rest",
  "graphql",
  "webpack",
  "vite",
  "nginx",
  "aws",
  "gcp",
  "azure",
  "linux",
  "git",
  "python",
  "javascript",
  "typescript",
  "rust",
  "go",
  "java",
  "sql",
  "postgresql",
  "mysql",
  "firebase",
  "supabase",
  "prisma",
  "sequelize",
  "tailwind",
  "css",
  "html",
  "sass",
  "scss",
  "bootstrap",
  "testing",
  "jest",
  "mocha",
  "cypress",
  "playwright",
  "ci",
  "cd",
  "pipeline",
  "deploy",
  "devops",
  "performance",
  "optimization",
  "caching",
  "security",
  "cors",
  "websocket",
  "ssr",
  "ssg",
  "hydration",
  "middleware",
  "proxy",
  "regex",
  "algorithm",
  "data-structure",
  "database",
  "migration",
  "debug",
  "error",
  "bug",
  "fix",
  "workaround",
  "config",
  "environment",
  "variable",
  "package",
  "dependency",
  "npm",
  "yarn",
  "pnpm",
  "monorepo",
  "microservice",
  "serverless",
  "lambda",
  "vercel",
  "netlify",
  "render",
  "heroku",
  "railway",
  "authentication",
  "authorization",
  "oauth",
  "session",
  "cookie",
  "encryption",
  "hashing",
  "bcrypt",
  "ssl",
  "tls",
  "https",
  "frontend",
  "backend",
  "fullstack",
  "component",
  "hook",
  "state",
  "redux",
  "zustand",
  "context",
  "provider",
  "router",
  "routing",
  "bash",
  "shell",
  "terminal",
  "cli",
  "command",
  "json",
  "xml",
  "yaml",
  "toml",
  "markdown",
  "svg",
  "canvas",
  "animation",
  "responsive",
  "mobile",
  "accessibility",
  "a11y",
  "seo",
  "pwa",
  "service-worker",
  "eslint",
  "prettier",
  "lint",
  "format",
  "typescript",
  "async",
  "await",
  "promise",
  "callback",
  "stream",
  "buffer",
  "file",
  "upload",
  "download",
  "storage",
  "email",
  "notification",
  "webhook",
  "cron",
  "scheduler",
  "chart",
  "graph",
  "visualization",
  "dashboard",
  "analytics",
]);

/**
 * Extract relevant developer tags from text content
 */
function extractTags(text, maxTags = 10) {
  if (!text || typeof text !== "string") return [];

  const combined = text.toLowerCase();

  // Extract keywords using keyword-extractor
  const extracted = keyword.extract(combined, {
    language: "english",
    remove_digits: false,
    return_changed_case: true,
    remove_duplicates: true,
  });

  // Match against dev dictionary
  const matched = extracted.filter((word) => DEV_DICTIONARY.has(word));

  // Also scan for multi-word dev terms
  const multiWordTerms = [
    "next.js",
    "node.js",
    "react native",
    "vue.js",
    "angular.js",
    "express.js",
    "data structure",
    "machine learning",
    "deep learning",
    "service worker",
    "web socket",
    "rate limit",
    "load balancer",
  ];

  for (const term of multiWordTerms) {
    if (combined.includes(term)) {
      matched.push(term.replace(/[.\s]/g, "-"));
    }
  }

  // Deduplicate and limit
  const unique = [...new Set(matched)];
  return unique.slice(0, maxTags);
}

module.exports = { extractTags, DEV_DICTIONARY };
